networks:
  dev:

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - dev

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - dev