version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Проброс порта для бэкенда, проверьте, есть ли он в вашем приложении
    env_file:
      - backend/.env  # Файл окружения, если он необходим

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Проброс порта для Nginx
